// Auto-generated by gen_do_execute.py

#include "../model_helper.h"
#include "model.h"

#include <cstdio>
#include <cstdlib>

[[noreturn]]
static ExecResult unimpl_cinst(const char* name) {
    fprintf(stderr, "unimplement c inst: %s\n", name);
    abort();
}

[[noreturn]]
static ExecResult unimpl_inst(const char* name) {
    fprintf(stderr, "unimplement inst: %s\n", name);
    abort();
}

[[noreturn]]
static void unimpl_csr_inspect(CsrIdx csr) {
    fprintf(stderr, "unimplemented csr inspect: 0x%03x\n", csr.idx);
    abort();
}

#include "_generated/unimpl_c.inc"
#include "_generated/unimpl.inc"

// 32-bit instruction implementations
#include "rvi/upper_imm.inc"
#include "rvi/control.inc"
#include "rvi/memory.inc"
#include "rvi/alu.inc"
#include "rvi/atomic.inc"
#include "rvi/system.inc"
#include "rvi/csr.inc"

// Compressed instruction implementations
#include "rvc/c_control.inc"
#include "rvc/c_arith.inc"
#include "rvc/c_mem.inc"

#include "_generated/do_execute_c.inc"
#include "_generated/do_execute.inc"

// CSR implementations
#include "csr/mmode.inc"
#include "csr/mmode_cfg.inc"
#include "_generated/unimpl_csr.inc"

ExecResult do_csr_rmw(CoreModel& core, CsrIdx csr, CsrOp op, uint32_t value, uint32_t* ret) {
  ExecResult res = do_csr_read(core, csr, ret);
  if (!res.is_ok()) return res;

  uint32_t new_value;
  switch (op) {
    case CsrOp::READ_WRITE: new_value = value; break;
    case CsrOp::READ_SET:   new_value = *ret | value; break;
    case CsrOp::READ_CLEAR: new_value = *ret & ~value; break;
  }

  return do_csr_write(core, csr, new_value);
}

#include "_generated/do_csr.inc"
